#Message-of-the-day content.
motd = """欢迎来到 TeaCon 2022 展示服务器
------------------------
请评审员和试玩员加入我们的 Kook 频道反馈问题 https://kook.teacon.cn 
------------------------
游览导引手册在官网首页 https://www.teacon.cn/2022 下载，请务必看看。
服务器会定期推送小提示，也许会对你的游览有帮助。
------------------------
Shimmer的泛光与彩光效果皆支持配置,可根据个人喜好进行调节、开关（游戏内可通过./shimmer指令设置）
详情参见 https://github.com/Low-Drag-MC/Shimmer/wiki
------------------------
玩得开心点"""
