owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0024af7b-f06c-4746-a08e-3ac89cec841c"
min = [ 400, -2147483648, -624 ]
max = [ 527, 2147483647, -497 ]
name = "TeaCon 2022 展示服务器 4c 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
