name = "builder_sunken_world"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0017a78b-441d-4d24-9505-c1b5e7025945"

[[permissions]]
permission = "area_control.*"
value = true

[permissions.context]
world = "world/sunken_world/sunken_world"

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
world = "world/sunken_world/sunken_world"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
world = "world/sunken_world/sunken_world"

[[permissions]]
permission = "area_control.command.*"
value = true

[permissions.context]
world = "world/sunken_world/sunken_world"

[[permissions]]
permission = "weight.10"
value = true
