name = "builder_creeper_firework"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0046afed-feba-49ae-83fb-df84c38e0d5e"

[[permissions]]
permission = "weight.10"
value = true
