name = "builder_boomood"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0047ad51-c5a1-409d-b742-b44ed6b85940"

[[permissions]]
permission = "weight.10"
value = true
