name = "builder_firecrafting"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0026f406-7783-4eff-b98d-8c388112cb5e"

[[permissions]]
permission = "weight.10"
value = true
